---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

```{r}
library(quantreg)
library(dplyr)
library(ggplot2)
library(gridExtra)
library(utils)
library(WRS2)

```

loading data
```{r}
H2data <- read.csv("Hypothesis 2 Data.csv")
H3data <- read.csv("Hypothesis 3 Data.csv")
FinalData <- read.csv("Historic and Modern Data.csv")
```

```{r}

t1 <- filter(FinalData, Species =="Aciphylla glacialis") %>%
  rq(GoogleElevation ~ Year, tau=c(.05,0.95),.)   # doing quantile regressions for individual species *change species name*

summary(t1, se = "boot") #running the bootstrap method to get p-values from the individual speices


myquantiles <- FinalData %>%
  group_by(Species) %>%
    do(model=rq(GoogleElevation ~ Year,  tau=c(.05,0.95), .)) #doing quantile regressions for ALL species (without p value)

quantiles <- as.data.frame(tidy(myquantiles, model))

write.csv(quantiles, "Quantile regressions.csv")
```

```{r}
H2Quantile <- read.csv("H2 Quantile Regressions.csv")
H3Quantile <- read.csv("H3 Quantile Regressions.csv")
Anovas <- read.csv("Anova Results.csv")

H2Quantile$HighPcorrected <- p.adjust(H2Quantile$High.Year.P.Value, "holm")  #doing p adjustments for multiple p values
H2Quantile$LowPcorrected <- p.adjust(H2Quantile$Low.Year.P.Value, "holm")
H3Quantile$LowPcorrected <- p.adjust(H3Quantile$Low.Year.P.Value, "holm")
Anovas$Pcorrected <- p.adjust(Anovas$P.value, "holm")



write.csv(H2Quantile, "H2 Quantile Regressions P Correct.csv")
write.csv(H3Quantile, "H3 Quantile Regressions P Correct.csv")


```

